sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
notifications:
  email: false
  irc:
    channels:
      secure: "Pa+ZfGVmPFpUGXWgvTK2xAdkF86rzPbpqJCFDOgM2BKuOLcGh7YMsXKOjNMFKS5kJN5wqE1BNCP6oDrq84iKVMkIp31bdHWj+HDWh88Ca7I6kCa0+A+Z/AkZInp0hN/V55pLd28YHdzEcJP0FEx39Rdt6gQ0f/GtqVpOwyhRrhm+Kz52wuWX1bX89wsKZ+woD9oReB6NCKDUKS/HsMLWVQOQZyTNDqkWe8iPwT4BbuxqCNmMWOGpL+tHkLO1HEvsUmEIOYcGO1LO5Syopg1OxHyIW1hsCzrmAKi1RZoC0uo3NUwkBtZhc16A+VVEDvy8ctbpTYvx3fwQ4i7LfTkpU4pGbj6PZFatFnhPB2Ux527I6mOWUMeUZ9yljclEXOIY3myq45xxvy0dybgsOCy1LzokEWrouM9ugzCvanlPzPGvkCSlr7iQk0SBEjkYI/E56f8nETsCSCu48OB8x0OjP/UmjTWNlfKD/2ezzto2lgtRejkW0UrnK14yFp4/xZCNBapXn4VTak1C0Z1nGiax5CGQKpTdg1KZZRQJCrz+S+OJVmRmez9lCxlfyE+cSZZIyD/lEccPn+pr6qjOCcCvx8jOu5clVIqlWjFYAK2c1QIKSnjfJpmX7eEJGibtwWuXJ3c5RNS8Gl0Lz0aEbse8zBoMCpoPj2nReaB8h312d6I="
    password:
      secure: "jGVTeJvUgksaI1rq7746kdH2d7XQIjvtv89GdsHD+cBtMfLxkc45ajJFSoRtSOPSkVwwt18z42ZiU00s6gbEGrDPGWKxmcZL8OrS5n4jStVbtMltxQBPQ37VlO/IIS9DwuEOQfJVPqjb0uJ/cXTD81mFA6EY0VGztfvjJPs8JmCAvbE7Ch5WBi5kEYdkdkLcMWzhxd7/WjDRoU4sBG4SlaKMUYF5dExlc8R1mn5LXHSvjwK1pMYdnHRtM6OFoWnSR1NnANlzT79/ESD+fbiDKPJ9wymkoia1v/lBqSramuYLjOl5dLiR3wF0CR3lpDDvsCt8nchySFcjwIQ+JJGUUrVj66m3XFuGVpfFdYeqnhAZwHQC8IpEnYQWt7OGOkVqmuhsSz0lYyB8HwzW+E8TTSFWBeA30ubEaQK1uwd63i1mv5O/E1wMvp5xxyrV7Oye5UY6Dmu/XulHuC3CsKW3wQT9jgYi3V4Y6VaXiYL+jGlcw7bFDQfkozKeGN/35pP/P/WRLmuogPocfHbTeJbyM3jm8YQwgAIZxKU0S16zQfA7VutIK4j0XJNOJqecka1StNumMmug6J+92YuXQc6mAhyvTEQ8tGNns7d/NChz7CJio/lrYIkhd2QhKeUaab88TkfQvDeArJ3VyISUC6UnmGjIrJLOuSx12zuqE0I/cR4="
